export const words = {
  LOGIN_PLACEHOLDER: 'Login',
  PASSWORD_PLACEHOLDER: 'Password',
  SIGN_IN: 'Sign in',
  REMEMBER: 'Remember me',
  FORGOT: 'Forgot Password',
  NO_ACCOUNT: 'Create a profile?',
  IS_ACCOUNT: 'Already have an account?',
  SIGN_UP: 'Sign up',
  FIRST_NAME: 'First name',
  SECOND_NAME: 'Last name',
  EMAIL: 'Email',
  PHONE: 'Phone',
  CONFIRM_PASSWORD: 'Confirm password',
  CONFIRM_POLICY: 'I Agree with',
  PRIVACY: 'privacy policy',
  PROFILE: "User's settings, change profile",
  CHANGE_AVATAR: 'Change avatar',
  DISPLAY_NAME: 'Dispaly name',
  OLD_PASSWORD: 'Old password',
  NEW_PASSWORD: 'New password',
  APPLY_CHANGES: 'Applay changes',
  NOT_FOUND: 'Page not found',
  NOT_FOUND_NUMBER: '404',
  SERVER_ERROR_NUMBER: '5**',
  SERVER_ERROR: "We're trying to cope with the problem",
  TO_HOME: 'Get back',
  CHATS_HEADER: 'Chats',
  SEARCH_PLACEHOLDER: 'Search',
};
